export const actionTypes = {
    ADMIN_FETCH_PAGINATION_DATA: 'ADMIN_FETCH_PAGINATION_DATA',
    FETCH_ALL_ADMINS: 'FETCH_ALL_ADMINS',
    FETCH_SELECTED_ADMIN: 'FETCH_SELECTED_ADMIN',

    ADMIN_SET_SEARCH_TERM: 'ADMIN_SET_SEARCH_TERM',
    ADMIN_SET_PAGINATION_DATA: 'ADMIN_SET_PAGINATION_DATA',

    ADD_NEW_ADMIN: 'ADD_NEW_ADMIN',
    UPDATE_ADMIN_DATA: 'UPDATE_ADMIN_DATA',
    DELETE_ADMIN: 'DELETE_ADMIN',

    CHANGE_ADMIN_PASSWORD: 'CHANGE_ADMIN_PASSWORD'
}