export const actionTypes = {
    FACULTY_FETCH_PAGINATION_DATA: 'FACULTY_FETCH_PAGINATION_DATA',
    FETCH_DD_FACULTIES: 'FETCH_DD_FACULTIES',
    FETCH_ALL_FACULTIES: 'FETCH_ALL_FACULTIES',
    FETCH_SELECTED_FACULTY: 'FETCH_SELECTED_FACULTY',

    FACULTY_SET_SEARCH_TERM: 'FACULTY_SET_SEARCH_TERM',
    FACULTY_SET_PAGINATION_DATA: 'FACULTY_SET_PAGINATION_DATA',

    ADD_NEW_FACULTY: 'ADD_NEW_FACULTY',
    UPDATE_FACULTY_DATA: 'UPDATE_FACULTY_DATA',
    DELETE_FACULTY: 'DELETE_FACULTY',
}