export const actionTypes = {
    STUDENT_FETCH_PAGINATION_DATA: 'STUDENT_FETCH_PAGINATION_DATA',
    FETCH_ALL_STUDENTS: 'FETCH_ALL_STUDENTS',

    STUDENT_SET_SEARCH_TERM: 'STUDENT_SET_SEARCH_TERM',
    STUDENT_SET_PAGINATION_DATA: 'STUDENT_SET_PAGINATION_DATA',

    ADD_NEW_STUDENT: 'ADD_NEW_STUDENT',
    UPDATE_STUDENT_DATA: 'UPDATE_STUDENT_DATA',
    DELETE_STUDENT: 'DELETE_STUDENT',

    CHANGE_STUDENT_PASSWORD: 'CHANGE_STUDENT_PASSWORD'
}