export const actionTypes = {
    TEACHER_FETCH_PAGINATION_DATA: 'TEACHER_FETCH_PAGINATION_DATA',
    FETCH_ALL_TEACHERS: 'FETCH_ALL_TEACHERS',

    TEACHER_SET_SEARCH_TERM: 'TEACHER_SET_SEARCH_TERM',
    TEACHER_SET_PAGINATION_DATA: 'TEACHER_SET_PAGINATION_DATA',

    ADD_NEW_TEACHER: 'ADD_NEW_TEACHER',
    UPDATE_TEACHER_DATA: 'UPDATE_TEACHER_DATA',
    DELETE_TEACHER: 'DELETE_TEACHER',

    CHANGE_TEACHER_PASSWORD: 'CHANGE_TEACHER_PASSWORD'
}