export const actionTypes = {
    FETCH_SELECTED_ASSIGNMENT: 'FETCH_SELECTED_ASSIGNMENT',
    FETCH_SELECTED_SUMBITTED_ASSIGNMENT: 'FETCH_SELECTED_SUMBITTED_ASSIGNMENT',
    FETCH_ALL_SPECIFIC_ASSIGNMENTS: 'FETCH_ALL_SPECIFIC_ASSIGNMENTS',
    FETCH_PAGINATION_DATA_ASSIGNMENT: 'FETCH_PAGINATION_DATA_ASSIGNMENT'
}