export const actionTypes = {
    FETCH_SELECTED_TEST_PAPER: 'FETCH_SELECTED_TEST_PAPER',
    FETCH_SELECTED_ANSWER_PAPER: 'FETCH_SELECTED_ANSWER_PAPER',
    FETCH_ALL_SPECIFIC_TESTS: 'FETCH_ALL_SPECIFIC_TESTS',
    FETCH_PAGINATION_DATA_TEST: 'FETCH_PAGINATION_DATA_TEST'
}