import {MyImg} from "../../constants/FillerImg";

export const teachers = [{
    "_id": 1,
    "profile": <MyImg/>,
    "name": "Jeremie",
    "email": "jthurborn0@amazon.com",
    "contact": "8648801393",
    "totalCourses": 2
}, {
    "_id": 2,
    "profile": <MyImg/>,
    "name": "Garvy",
    "email": "gdominka1@un.org",
    "contact": "4235180573",
    "totalCourses": 9
}, {
    "_id": 3,
    "profile": <MyImg/>,
    "name": "Lucie",
    "email": "lmarians2@gizmodo.com",
    "contact": "2857755553",
    "totalCourses": 7
}, {
    "_id": 4,
    "profile": <MyImg/>,
    "name": "Amalia",
    "email": "amctrustie3@infoseek.co.jp",
    "contact": "3001883717",
    "totalCourses": 6
}, {
    "_id": 5,
    "profile": <MyImg/>,
    "name": "Ashlie",
    "email": "agavin4@networkadvertising.org",
    "contact": "4241490508",
    "totalCourses": 9
}, {
    "_id": 6,
    "profile": <MyImg/>,
    "name": "Abbye",
    "email": "agoghin5@sciencedaily.com",
    "contact": "9506595224",
    "totalCourses": 6
}, {
    "_id": 7,
    "profile": <MyImg/>,
    "name": "Lyman",
    "email": "lphelan6@ftc.gov",
    "contact": "3522967598",
    "totalCourses": 8
}, {
    "_id": 8,
    "profile": <MyImg/>,
    "name": "Smith",
    "email": "ssmythin7@intel.com",
    "contact": "3496625652",
    "totalCourses": 3
}, {
    "_id": 9,
    "profile": <MyImg/>,
    "name": "Christiane",
    "email": "cbehrens8@parallels.com",
    "contact": "1416306129",
    "totalCourses": 10
}, {
    "_id": 10,
    "profile": <MyImg/>,
    "name": "Winne",
    "email": "wmcmichael9@eepurl.com",
    "contact": "3239849761",
    "totalCourses": 7
}, {
    "_id": 11,
    "profile": <MyImg/>,
    "name": "Goraud",
    "email": "gstrangera@indiegogo.com",
    "contact": "5955297227",
    "totalCourses": 6
}, {
    "_id": 12,
    "profile": <MyImg/>,
    "name": "Gena",
    "email": "ggossingtonb@cloudflare.com",
    "contact": "7779041257",
    "totalCourses": 9
}, {
    "_id": 13,
    "profile": <MyImg/>,
    "name": "Eada",
    "email": "ekanterc@wisc.edu",
    "contact": "6178373739",
    "totalCourses": 5
}, {
    "_id": 14,
    "profile": <MyImg/>,
    "name": "Silvie",
    "email": "sshawyerd@macromedia.com",
    "contact": "1753587219",
    "totalCourses": 7
}, {
    "_id": 15,
    "profile": <MyImg/>,
    "name": "Fredrick",
    "email": "formstone@guardian.co.uk",
    "contact": "4493828295",
    "totalCourses": 8
}, {
    "_id": 16,
    "profile": <MyImg/>,
    "name": "Theresina",
    "email": "tpanimanf@google.es",
    "contact": "5496532359",
    "totalCourses": 9
}, {
    "_id": 17,
    "profile": <MyImg/>,
    "name": "Odessa",
    "email": "ocumpstyg@boston.com",
    "contact": "4713025936",
    "totalCourses": 5
}, {
    "_id": 18,
    "profile": <MyImg/>,
    "name": "Ashely",
    "email": "apadlyh@bbc.co.uk",
    "contact": "6504036145",
    "totalCourses": 1
}, {
    "_id": 19,
    "profile": <MyImg/>,
    "name": "Judi",
    "email": "jhundalli@goodreads.com",
    "contact": "8405435824",
    "totalCourses": 4
}, {
    "_id": 20,
    "profile": <MyImg/>,
    "name": "Allyn",
    "email": "agomezj@salon.com",
    "contact": "4898133140",
    "totalCourses": 4
}, {
    "_id": 21,
    "profile": <MyImg/>,
    "name": "Lonnie",
    "email": "ljobernk@miitbeian.gov.cn",
    "contact": "1175057602",
    "totalCourses": 6
}, {
    "_id": 22,
    "profile": <MyImg/>,
    "name": "Doralin",
    "email": "dseczykl@hostgator.com",
    "contact": "8995499470",
    "totalCourses": 3
}, {
    "_id": 23,
    "profile": <MyImg/>,
    "name": "Rees",
    "email": "relanm@ifeng.com",
    "contact": "5114609284",
    "totalCourses": 6
}, {
    "_id": 24,
    "profile": <MyImg/>,
    "name": "Penn",
    "email": "pdablinn@aboutads.info",
    "contact": "6362261290",
    "totalCourses": 10
}, {
    "_id": 25,
    "profile": <MyImg/>,
    "name": "Filmore",
    "email": "fdringo@liveinternet.ru",
    "contact": "3537608932",
    "totalCourses": 8
}, {
    "_id": 26,
    "profile": <MyImg/>,
    "name": "Paulie",
    "email": "pdowsonp@networkadvertising.org",
    "contact": "3042524950",
    "totalCourses": 8
}, {
    "_id": 27,
    "profile": <MyImg/>,
    "name": "Consuela",
    "email": "cwarboyq@statcounter.com",
    "contact": "8605819171",
    "totalCourses": 7
}, {
    "_id": 28,
    "profile": <MyImg/>,
    "name": "Seward",
    "email": "ssmalecomber@cafepress.com",
    "contact": "8502208111",
    "totalCourses": 5
}, {
    "_id": 29,
    "profile": <MyImg/>,
    "name": "Adina",
    "email": "acaysers@ow.ly",
    "contact": "5611628672",
    "totalCourses": 1
}, {
    "_id": 30,
    "profile": <MyImg/>,
    "name": "Christiane",
    "email": "cjedrasikt@vinaora.com",
    "contact": "1309845581",
    "totalCourses": 2
}, {
    "_id": 31,
    "profile": <MyImg/>,
    "name": "Tabbie",
    "email": "tsteuhlmeyeru@smh.com.au",
    "contact": "8501068544",
    "totalCourses": 3
}, {
    "_id": 32,
    "profile": <MyImg/>,
    "name": "Rowena",
    "email": "rgriggsv@noaa.gov",
    "contact": "3848571600",
    "totalCourses": 5
}, {
    "_id": 33,
    "profile": <MyImg/>,
    "name": "Delila",
    "email": "dholtomw@t.co",
    "contact": "6931818642",
    "totalCourses": 10
}, {
    "_id": 34,
    "profile": <MyImg/>,
    "name": "Roddie",
    "email": "rgammelx@blogger.com",
    "contact": "8929872706",
    "totalCourses": 5
}, {
    "_id": 35,
    "profile": <MyImg/>,
    "name": "Rosmunda",
    "email": "rdurtnely@rediff.com",
    "contact": "6346297001",
    "totalCourses": 7
}, {
    "_id": 36,
    "profile": <MyImg/>,
    "name": "Jerad",
    "email": "jsentz@cbslocal.com",
    "contact": "3168712385",
    "totalCourses": 4
}, {
    "_id": 37,
    "profile": <MyImg/>,
    "name": "Andrew",
    "email": "awells10@hc360.com",
    "contact": "5567339322",
    "totalCourses": 10
}, {
    "_id": 38,
    "profile": <MyImg/>,
    "name": "Ritchie",
    "email": "ryerill11@imageshack.us",
    "contact": "1846567871",
    "totalCourses": 5
}, {
    "_id": 39,
    "profile": <MyImg/>,
    "name": "Isis",
    "email": "itorns12@4shared.com",
    "contact": "2806739948",
    "totalCourses": 8
}, {
    "_id": 40,
    "profile": <MyImg/>,
    "name": "Davie",
    "email": "dcleaves13@samsung.com",
    "contact": "5293946359",
    "totalCourses": 4
}];


























export const students = [{
    "_id": 1,
    "profile": <MyImg/>,
    "name": "Roma",
    "email": "rkleinert0@google.com.br",
    "contact": "5502175312",
    "totalCourses": 2
}, {
    "_id": 2,
    "profile": <MyImg/>,
    "name": "Rickie",
    "email": "rdurrand1@elpais.com",
    "contact": "5653979890",
    "totalCourses": 3
}, {
    "_id": 3,
    "profile": <MyImg/>,
    "name": "Nancie",
    "email": "ncherrington2@weibo.com",
    "contact": "7578143671",
    "totalCourses": 10
}, {
    "_id": 4,
    "profile": <MyImg/>,
    "name": "Godard",
    "email": "gmcdougle3@purevolume.com",
    "contact": "1371774743",
    "totalCourses": 5
}, {
    "_id": 5,
    "profile": <MyImg/>,
    "name": "Giorgia",
    "email": "gstoller4@reference.com",
    "contact": "2394407106",
    "totalCourses": 7
}, {
    "_id": 6,
    "profile": <MyImg/>,
    "name": "Yvette",
    "email": "ydaintier5@dion.ne.jp",
    "contact": "5907486110",
    "totalCourses": 8
}, {
    "_id": 7,
    "profile": <MyImg/>,
    "name": "Dionisio",
    "email": "dpeert6@yandex.ru",
    "contact": "8112558470",
    "totalCourses": 4
}, {
    "_id": 8,
    "profile": <MyImg/>,
    "name": "Olenolin",
    "email": "omeritt7@slideshare.net",
    "contact": "9044770572",
    "totalCourses": 9
}, {
    "_id": 9,
    "profile": <MyImg/>,
    "name": "Dianemarie",
    "email": "droos8@angelfire.com",
    "contact": "8531063475",
    "totalCourses": 6
}, {
    "_id": 10,
    "profile": <MyImg/>,
    "name": "Shanon",
    "email": "sdroghan9@techcrunch.com",
    "contact": "1383738542",
    "totalCourses": 10
}, {
    "_id": 11,
    "profile": <MyImg/>,
    "name": "Renado",
    "email": "rkightlya@businessinsider.com",
    "contact": "9026705187",
    "totalCourses": 10
}, {
    "_id": 12,
    "profile": <MyImg/>,
    "name": "Tish",
    "email": "tshuttlewoodb@addtoany.com",
    "contact": "2496981809",
    "totalCourses": 10
}, {
    "_id": 13,
    "profile": <MyImg/>,
    "name": "Holden",
    "email": "htarbinc@independent.co.uk",
    "contact": "8487693170",
    "totalCourses": 6
}, {
    "_id": 14,
    "profile": <MyImg/>,
    "name": "Hyacinthie",
    "email": "hbythelld@jalbum.net",
    "contact": "7488380482",
    "totalCourses": 2
}, {
    "_id": 15,
    "profile": <MyImg/>,
    "name": "Cecile",
    "email": "cmintoffe@google.co.jp",
    "contact": "5397899369",
    "totalCourses": 6
}, {
    "_id": 16,
    "profile": <MyImg/>,
    "name": "Otha",
    "email": "oaymerichf@pbs.org",
    "contact": "6331985708",
    "totalCourses": 2
}, {
    "_id": 17,
    "profile": <MyImg/>,
    "name": "Orville",
    "email": "obabbsg@disqus.com",
    "contact": "2461348808",
    "totalCourses": 2
}, {
    "_id": 18,
    "profile": <MyImg/>,
    "name": "Correy",
    "email": "childredh@cbslocal.com",
    "contact": "6996795506",
    "totalCourses": 2
}, {
    "_id": 19,
    "profile": <MyImg/>,
    "name": "Christyna",
    "email": "cgodballi@sogou.com",
    "contact": "4708685017",
    "totalCourses": 8
}, {
    "_id": 20,
    "profile": <MyImg/>,
    "name": "Nonie",
    "email": "nmccaguej@rambler.ru",
    "contact": "2646129952",
    "totalCourses": 7
}, {
    "_id": 21,
    "profile": <MyImg/>,
    "name": "Nertie",
    "email": "nstonelakek@foxnews.com",
    "contact": "1657281112",
    "totalCourses": 4
}, {
    "_id": 22,
    "profile": <MyImg/>,
    "name": "Buddy",
    "email": "bskokoel@reuters.com",
    "contact": "7155408495",
    "totalCourses": 10
}, {
    "_id": 23,
    "profile": <MyImg/>,
    "name": "Nikki",
    "email": "ngarrishm@fastcompany.com",
    "contact": "2917311098",
    "totalCourses": 5
}, {
    "_id": 24,
    "profile": <MyImg/>,
    "name": "Stinky",
    "email": "sfadern@gmpg.org",
    "contact": "6188572941",
    "totalCourses": 9
}, {
    "_id": 25,
    "profile": <MyImg/>,
    "name": "Nadia",
    "email": "ngoodsello@amazonaws.com",
    "contact": "6775657013",
    "totalCourses": 5
}, {
    "_id": 26,
    "profile": <MyImg/>,
    "name": "Boycey",
    "email": "bpockettp@ebay.com",
    "contact": "8786099577",
    "totalCourses": 9
}, {
    "_id": 27,
    "profile": <MyImg/>,
    "name": "Orran",
    "email": "omcrorieq@addtoany.com",
    "contact": "5763822215",
    "totalCourses": 4
}, {
    "_id": 28,
    "profile": <MyImg/>,
    "name": "Wade",
    "email": "wcleer@prweb.com",
    "contact": "4215030554",
    "totalCourses": 8
}, {
    "_id": 29,
    "profile": <MyImg/>,
    "name": "Charla",
    "email": "ctweddells@guardian.co.uk",
    "contact": "4655627056",
    "totalCourses": 6
}, {
    "_id": 30,
    "profile": <MyImg/>,
    "name": "Burton",
    "email": "bkuschekt@cpanel.net",
    "contact": "7794936697",
    "totalCourses": 5
}, {
    "_id": 31,
    "profile": <MyImg/>,
    "name": "Ricky",
    "email": "rbagenalu@joomla.org",
    "contact": "7713606926",
    "totalCourses": 9
}, {
    "_id": 32,
    "profile": <MyImg/>,
    "name": "Leopold",
    "email": "lfrewv@wp.com",
    "contact": "9333577362",
    "totalCourses": 4
}, {
    "_id": 33,
    "profile": <MyImg/>,
    "name": "Raimund",
    "email": "rmcgormanw@unc.edu",
    "contact": "1544020401",
    "totalCourses": 7
}, {
    "_id": 34,
    "profile": <MyImg/>,
    "name": "Alric",
    "email": "agatenbyx@ameblo.jp",
    "contact": "9013346811",
    "totalCourses": 6
}, {
    "_id": 35,
    "profile": <MyImg/>,
    "name": "Rodolfo",
    "email": "rwarehamy@mail.ru",
    "contact": "9673625598",
    "totalCourses": 8
}, {
    "_id": 36,
    "profile": <MyImg/>,
    "name": "Edyth",
    "email": "egelemanz@elpais.com",
    "contact": "9712857475",
    "totalCourses": 1
}, {
    "_id": 37,
    "profile": <MyImg/>,
    "name": "Trudey",
    "email": "tanstiss10@unc.edu",
    "contact": "2423128727",
    "totalCourses": 5
}, {
    "_id": 38,
    "profile": <MyImg/>,
    "name": "Cecilia",
    "email": "cattock11@gnu.org",
    "contact": "9013836903",
    "totalCourses": 2
}, {
    "_id": 39,
    "profile": <MyImg/>,
    "name": "Bealle",
    "email": "bthewles12@nasa.gov",
    "contact": "7821270498",
    "totalCourses": 8
}, {
    "_id": 40,
    "profile": <MyImg/>,
    "name": "Bradford",
    "email": "bpraundlin13@pinterest.com",
    "contact": "2453587432",
    "totalCourses": 4
}, {
    "_id": 41,
    "profile": <MyImg/>,
    "name": "Jasun",
    "email": "jbier14@w3.org",
    "contact": "3403973556",
    "totalCourses": 7
}, {
    "_id": 42,
    "profile": <MyImg/>,
    "name": "Cindelyn",
    "email": "cobrogan15@wsj.com",
    "contact": "3207468227",
    "totalCourses": 1
}, {
    "_id": 43,
    "profile": <MyImg/>,
    "name": "Rayshell",
    "email": "rpinckard16@hugedomains.com",
    "contact": "1753166659",
    "totalCourses": 1
}, {
    "_id": 44,
    "profile": <MyImg/>,
    "name": "Gloriane",
    "email": "gpocock17@parallels.com",
    "contact": "6237267657",
    "totalCourses": 10
}, {
    "_id": 45,
    "profile": <MyImg/>,
    "name": "Karl",
    "email": "kpellett18@simplemachines.org",
    "contact": "6237074641",
    "totalCourses": 4
}, {
    "_id": 46,
    "profile": <MyImg/>,
    "name": "Stefan",
    "email": "ssandeland19@comcast.net",
    "contact": "6975469729",
    "totalCourses": 7
}, {
    "_id": 47,
    "profile": <MyImg/>,
    "name": "Brandais",
    "email": "bbertelet1a@chicagotribune.com",
    "contact": "3984035575",
    "totalCourses": 4
}, {
    "_id": 48,
    "profile": <MyImg/>,
    "name": "Jaymie",
    "email": "jpendock1b@army.mil",
    "contact": "5989051258",
    "totalCourses": 1
}, {
    "_id": 49,
    "profile": <MyImg/>,
    "name": "Rowney",
    "email": "rcready1c@ovh.net",
    "contact": "3019166566",
    "totalCourses": 5
}, {
    "_id": 50,
    "profile": <MyImg/>,
    "name": "Andre",
    "email": "awickes1d@networksolutions.com",
    "contact": "3384280394",
    "totalCourses": 10
}, {
    "_id": 51,
    "profile": <MyImg/>,
    "name": "Bobbette",
    "email": "bprozillo1e@networkadvertising.org",
    "contact": "7019670473",
    "totalCourses": 2
}, {
    "_id": 52,
    "profile": <MyImg/>,
    "name": "Shawn",
    "email": "scarrabot1f@reddit.com",
    "contact": "3699572804",
    "totalCourses": 3
}, {
    "_id": 53,
    "profile": <MyImg/>,
    "name": "Rycca",
    "email": "rgreggs1g@alibaba.com",
    "contact": "2316724284",
    "totalCourses": 4
}, {
    "_id": 54,
    "profile": <MyImg/>,
    "name": "Jodi",
    "email": "jalti1h@adobe.com",
    "contact": "7864354841",
    "totalCourses": 9
}, {
    "_id": 55,
    "profile": <MyImg/>,
    "name": "Mortie",
    "email": "mcallear1i@deviantart.com",
    "contact": "1156567280",
    "totalCourses": 5
}, {
    "_id": 56,
    "profile": <MyImg/>,
    "name": "Rania",
    "email": "rcrosetti1j@bluehost.com",
    "contact": "4704502700",
    "totalCourses": 1
}, {
    "_id": 57,
    "profile": <MyImg/>,
    "name": "Merrill",
    "email": "madolf1k@tinyurl.com",
    "contact": "3031181894",
    "totalCourses": 4
}, {
    "_id": 58,
    "profile": <MyImg/>,
    "name": "Mortimer",
    "email": "mmizzen1l@usda.gov",
    "contact": "8744079689",
    "totalCourses": 1
}, {
    "_id": 59,
    "profile": <MyImg/>,
    "name": "Elsi",
    "email": "eclimson1m@army.mil",
    "contact": "4984574027",
    "totalCourses": 2
}, {
    "_id": 60,
    "profile": <MyImg/>,
    "name": "Regan",
    "email": "rshearman1n@php.net",
    "contact": "8783014642",
    "totalCourses": 4
}, {
    "_id": 61,
    "profile": <MyImg/>,
    "name": "Kirsti",
    "email": "kgiff1o@ameblo.jp",
    "contact": "1234962528",
    "totalCourses": 4
}, {
    "_id": 62,
    "profile": <MyImg/>,
    "name": "Henka",
    "email": "htocqueville1p@army.mil",
    "contact": "4146382387",
    "totalCourses": 5
}, {
    "_id": 63,
    "profile": <MyImg/>,
    "name": "Lyn",
    "email": "lyurov1q@va.gov",
    "contact": "2014926627",
    "totalCourses": 2
}, {
    "_id": 64,
    "profile": <MyImg/>,
    "name": "Barry",
    "email": "bleyrroyd1r@joomla.org",
    "contact": "9911068929",
    "totalCourses": 4
}, {
    "_id": 65,
    "profile": <MyImg/>,
    "name": "Dionysus",
    "email": "damor1s@jigsy.com",
    "contact": "5006979281",
    "totalCourses": 6
}, {
    "_id": 66,
    "profile": <MyImg/>,
    "name": "Kelsi",
    "email": "kronan1t@mtv.com",
    "contact": "5252944877",
    "totalCourses": 6
}, {
    "_id": 67,
    "profile": <MyImg/>,
    "name": "Tonia",
    "email": "temslie1u@ycombinator.com",
    "contact": "4458570609",
    "totalCourses": 1
}, {
    "_id": 68,
    "profile": <MyImg/>,
    "name": "Barb",
    "email": "bbrisbane1v@hostgator.com",
    "contact": "1139012688",
    "totalCourses": 6
}, {
    "_id": 69,
    "profile": <MyImg/>,
    "name": "Reginauld",
    "email": "rbaine1w@tripod.com",
    "contact": "2114123905",
    "totalCourses": 8
}, {
    "_id": 70,
    "profile": <MyImg/>,
    "name": "Johnathan",
    "email": "jshawyer1x@cnet.com",
    "contact": "3916820479",
    "totalCourses": 2
}, {
    "_id": 71,
    "profile": <MyImg/>,
    "name": "Amble",
    "email": "apaulitschke1y@cpanel.net",
    "contact": "2505820597",
    "totalCourses": 5
}, {
    "_id": 72,
    "profile": <MyImg/>,
    "name": "Aguie",
    "email": "awince1z@indiegogo.com",
    "contact": "6489181315",
    "totalCourses": 7
}, {
    "_id": 73,
    "profile": <MyImg/>,
    "name": "Rhoda",
    "email": "rsotworth20@yale.edu",
    "contact": "5493736984",
    "totalCourses": 10
}, {
    "_id": 74,
    "profile": <MyImg/>,
    "name": "Bernette",
    "email": "btrattles21@weibo.com",
    "contact": "6988193581",
    "totalCourses": 2
}, {
    "_id": 75,
    "profile": <MyImg/>,
    "name": "Antonius",
    "email": "agritsunov22@google.cn",
    "contact": "1871235636",
    "totalCourses": 1
}, {
    "_id": 76,
    "profile": <MyImg/>,
    "name": "Gabriele",
    "email": "gcalvard23@cornell.edu",
    "contact": "2785702285",
    "totalCourses": 5
}, {
    "_id": 77,
    "profile": <MyImg/>,
    "name": "Carolyne",
    "email": "clathom24@squidoo.com",
    "contact": "1625190037",
    "totalCourses": 7
}, {
    "_id": 78,
    "profile": <MyImg/>,
    "name": "Bobby",
    "email": "btelling25@phoca.cz",
    "contact": "5742451918",
    "totalCourses": 6
}, {
    "_id": 79,
    "profile": <MyImg/>,
    "name": "Mildrid",
    "email": "mlowis26@msu.edu",
    "contact": "5612404384",
    "totalCourses": 6
}, {
    "_id": 80,
    "profile": <MyImg/>,
    "name": "Fran",
    "email": "frolstone27@ucoz.ru",
    "contact": "8501117561",
    "totalCourses": 4
}, {
    "_id": 81,
    "profile": <MyImg/>,
    "name": "Cornelius",
    "email": "cbroker28@archive.org",
    "contact": "5082077342",
    "totalCourses": 5
}, {
    "_id": 82,
    "profile": <MyImg/>,
    "name": "Francesco",
    "email": "fborge29@upenn.edu",
    "contact": "1459415475",
    "totalCourses": 9
}, {
    "_id": 83,
    "profile": <MyImg/>,
    "name": "York",
    "email": "yjosilevich2a@mapquest.com",
    "contact": "2352863885",
    "totalCourses": 7
}, {
    "_id": 84,
    "profile": <MyImg/>,
    "name": "Lincoln",
    "email": "lbartleman2b@i2i.jp",
    "contact": "7625522562",
    "totalCourses": 4
}, {
    "_id": 85,
    "profile": <MyImg/>,
    "name": "Arabelle",
    "email": "aeyers2c@uol.com.br",
    "contact": "8121662545",
    "totalCourses": 2
}, {
    "_id": 86,
    "profile": <MyImg/>,
    "name": "Verine",
    "email": "vmackilpatrick2d@feedburner.com",
    "contact": "9315823691",
    "totalCourses": 10
}, {
    "_id": 87,
    "profile": <MyImg/>,
    "name": "Hilliard",
    "email": "hclitsome2e@slideshare.net",
    "contact": "1727809154",
    "totalCourses": 9
}, {
    "_id": 88,
    "profile": <MyImg/>,
    "name": "Maxie",
    "email": "msainsberry2f@vinaora.com",
    "contact": "3697151153",
    "totalCourses": 10
}, {
    "_id": 89,
    "profile": <MyImg/>,
    "name": "Una",
    "email": "ustanmore2g@omniture.com",
    "contact": "9617134719",
    "totalCourses": 4
}, {
    "_id": 90,
    "profile": <MyImg/>,
    "name": "Maurice",
    "email": "mkarlolczak2h@businessweek.com",
    "contact": "7417447891",
    "totalCourses": 1
}, {
    "_id": 91,
    "profile": <MyImg/>,
    "name": "Daryl",
    "email": "dlanbertoni2i@amazon.de",
    "contact": "6938839154",
    "totalCourses": 3
}, {
    "_id": 92,
    "profile": <MyImg/>,
    "name": "Sydelle",
    "email": "skohlert2j@oaic.gov.au",
    "contact": "2693625792",
    "totalCourses": 8
}, {
    "_id": 93,
    "profile": <MyImg/>,
    "name": "Daffi",
    "email": "dburgis2k@utexas.edu",
    "contact": "6359010020",
    "totalCourses": 2
}, {
    "_id": 94,
    "profile": <MyImg/>,
    "name": "Ave",
    "email": "araft2l@odnoklassniki.ru",
    "contact": "4179163916",
    "totalCourses": 8
}, {
    "_id": 95,
    "profile": <MyImg/>,
    "name": "Gwyn",
    "email": "gmatusiak2m@xinhuanet.com",
    "contact": "6462850537",
    "totalCourses": 2
}, {
    "_id": 96,
    "profile": <MyImg/>,
    "name": "Birdie",
    "email": "bworland2n@etsy.com",
    "contact": "2279769600",
    "totalCourses": 2
}, {
    "_id": 97,
    "profile": <MyImg/>,
    "name": "Marni",
    "email": "mmckinty2o@newsvine.com",
    "contact": "9004538260",
    "totalCourses": 3
}, {
    "_id": 98,
    "profile": <MyImg/>,
    "name": "Letizia",
    "email": "ltirrey2p@qq.com",
    "contact": "9567383619",
    "totalCourses": 9
}, {
    "_id": 99,
    "profile": <MyImg/>,
    "name": "Farrel",
    "email": "fchilds2q@sogou.com",
    "contact": "7932016289",
    "totalCourses": 3
}, {
    "_id": 100,
    "profile": <MyImg/>,
    "name": "Flemming",
    "email": "falexandersson2r@pagesperso-orange.fr",
    "contact": "9511595941",
    "totalCourses": 7
}];




























export const courses = [{
    "_id": 1,
    "name": "Hill",
    "faculty": "BGE",
    "students": 311,
    "teachers": 5
}, {
    "_id": 2,
    "name": "Court",
    "faculty": "WUX",
    "students": 206,
    "teachers": 20
}, {
    "_id": 3,
    "name": "Center",
    "faculty": "SMH",
    "students": 250,
    "teachers": 5
}, {
    "_id": 4,
    "name": "Alley",
    "faculty": "RGE",
    "students": 753,
    "teachers": 12
}, {
    "_id": 5,
    "name": "Parkway",
    "faculty": "MYK",
    "students": 389,
    "teachers": 7
}, {
    "_id": 6,
    "name": "Road",
    "faculty": "DMA",
    "students": 358,
    "teachers": 3
}, {
    "_id": 7,
    "name": "Alley",
    "faculty": "JON",
    "students": 847,
    "teachers": 5
}, {
    "_id": 8,
    "name": "Lane",
    "faculty": "OSL",
    "students": 257,
    "teachers": 7
}, {
    "_id": 9,
    "name": "Crossing",
    "faculty": "HIM",
    "students": 687,
    "teachers": 4
}, {
    "_id": 10,
    "name": "Alley",
    "faculty": "DGE",
    "students": 383,
    "teachers": 15
}, {
    "_id": 11,
    "name": "Court",
    "faculty": "DMA",
    "students": 432,
    "teachers": 6
}, {
    "_id": 12,
    "name": "Pass",
    "faculty": "ZAM",
    "students": 471,
    "teachers": 10
}, {
    "_id": 13,
    "name": "Court",
    "faculty": "SNT",
    "students": 534,
    "teachers": 20
}, {
    "_id": 14,
    "name": "Center",
    "faculty": "SPW",
    "students": 419,
    "teachers": 10
}, {
    "_id": 15,
    "name": "Parkway",
    "faculty": "OSY",
    "students": 165,
    "teachers": 16
}, {
    "_id": 16,
    "name": "Point",
    "faculty": "NMN",
    "students": 595,
    "teachers": 19
}, {
    "_id": 17,
    "name": "Point",
    "faculty": "TML",
    "students": 635,
    "teachers": 8
}, {
    "_id": 18,
    "name": "Drive",
    "faculty": "SYD",
    "students": 337,
    "teachers": 2
}, {
    "_id": 19,
    "name": "Street",
    "faculty": "YMT",
    "students": 929,
    "teachers": 7
}, {
    "_id": 20,
    "name": "Hill",
    "faculty": "CLV",
    "students": 459,
    "teachers": 19
}, {
    "_id": 21,
    "name": "Drive",
    "faculty": "BFG",
    "students": 54,
    "teachers": 19
}, {
    "_id": 22,
    "name": "Place",
    "faculty": "YFJ",
    "students": 790,
    "teachers": 3
}, {
    "_id": 23,
    "name": "Park",
    "faculty": "RKE",
    "students": 627,
    "teachers": 8
}, {
    "_id": 24,
    "name": "Plaza",
    "faculty": "NHD",
    "students": 76,
    "teachers": 1
}, {
    "_id": 25,
    "name": "Hill",
    "faculty": "ECO",
    "students": 476,
    "teachers": 8
}, {
    "_id": 26,
    "name": "Junction",
    "faculty": "CFO",
    "students": 460,
    "teachers": 9
}, {
    "_id": 27,
    "name": "Way",
    "faculty": "WME",
    "students": 597,
    "teachers": 12
}, {
    "_id": 28,
    "name": "Place",
    "faculty": "MQH",
    "students": 69,
    "teachers": 2
}, {
    "_id": 29,
    "name": "Drive",
    "faculty": "IOU",
    "students": 912,
    "teachers": 20
}, {
    "_id": 30,
    "name": "Parkway",
    "faculty": "THE",
    "students": 790,
    "teachers": 13
}];



















export const faculties = [{
    "_id": 1,
    "name": "Budd",
    "courses": 44
}, {
    "_id": 2,
    "name": "Gray",
    "courses": 54
}, {
    "_id": 3,
    "name": "Cort",
    "courses": 21
}, {
    "_id": 4,
    "name": "Maisie",
    "courses": 79
}, {
    "_id": 5,
    "name": "Charissa",
    "courses": 7
}, {
    "_id": 6,
    "name": "Yevette",
    "courses": 56
}, {
    "_id": 7,
    "name": "Dodie",
    "courses": 11
}, {
    "_id": 8,
    "name": "Kilian",
    "courses": 56
}, {
    "_id": 9,
    "name": "Carilyn",
    "courses": 39
}, {
    "_id": 10,
    "name": "Bradly",
    "courses": 45
}];