export const actionTypes = {
    FETCH_HEAD_INFO: 'FETCH_HEAD_INFO',

    FETCH_TEST_PROGRESS_DATA: 'FETCH_TEST_PROGRESS_DATA',
    FETCH_ASSIGNMENT_PROGRESS_DATA: 'FETCH_ASSIGNMENT_PROGRESS_DATA',

    FETCH_COURSE_STAT: 'FETCH_COURSE_STAT',
    FETCH_ASSIGNMENT_STAT: 'FETCH_ASSIGNMENT_STAT',
    FETCH_TEST_STAT: 'FETCH_TEST_STAT',

    FETCH_STUDENTS: 'FETCH_STUDENTS'
}