export const actionTypes = {
    COURSE_FETCH_PAGINATION_DATA: 'COURSE_FETCH_PAGINATION_DATA',
    FETCH_ALL_COURSES: 'FETCH_ALL_COURSES',

    COURSE_SET_SEARCH_TERM: 'COURSE_SET_SEARCH_TERM',
    COURSE_SET_PAGINATION_DATA: 'COURSE_SET_PAGINATION_DATA',

    ADD_NEW_COURSE: 'ADD_NEW_COURSE',
    UPDATE_COURSE_DATA: 'UPDATE_COURSE_DATA',
    DELETE_COURSE: 'DELETE_COURSE',
}