export const actionTypes = {
    COURSE_FETCH_PAGINATION_DATA: 'COURSE_FETCH_PAGINATION_DATA',
    FETCH_ALL_COURSES: 'FETCH_ALL_COURSES',
    FETCH_SELECTED_COURSE: 'FETCH_SELECTED_COURSE',
    FETCH_FACULTY_COURSES: 'FETCH_FACULTY_COURSES',
    FETCH_FACULTY_COURSE_PAGINATION: 'FETCH_FACULTY_COURSE_PAGINATION',

    COURSE_SET_SEARCH_TERM: 'COURSE_SET_SEARCH_TERM',
    FACULTY_COURSE_SET_SEARCH_TERM: 'FACULTY_COURSE_SET_SEARCH_TERM',
    COURSE_SET_PAGINATION_DATA: 'COURSE_SET_PAGINATION_DATA',

    ADD_NEW_COURSE: 'ADD_NEW_COURSE',
    UPDATE_COURSE_DATA: 'UPDATE_COURSE_DATA',
    DELETE_COURSE: 'DELETE_COURSE',

    UPDATE_SELECTION_PURPOSE: 'UPDATE_SELECTION_PURPOSE',

    ADD_USER_TO_COURSE: 'ADD_USER_TO_COURSE',
    REMOVE_USER_FROM_COURSE: 'REMOVE_USER_FROM_COURSE'
}